### ISSUE TITLE
Error in Parser.php

### ISSUE THREAD

**Issue by LanceSpicer** [usdoj/singletablefacets#15]
I have successfully installed and configured your single table facets in a development environment. However, when I moved my project to a production server, I am now getting this fatal error: 

Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in
singletablefacets-master\vendor\symfony\yaml\Symfony\Component\Yaml\Parser.php on line 368

Unlike my development environment, It appears the $value passed to ParseValue is truncated on the production version (it's missing some values from the yml file). I'm not sure why this would be. Any help is greatly appreciated. Thank you for all your work!

**Comment by brockfanning** [comment]
Hi @LanceSpicer, I don't remember running into that issue. I'd probably start by looking for any differences between the YAML you're using on dev, versus the YAML you're using on production. I know YAML can be pretty picky about indentation and extra/missing spaces.

**Comment by LanceSpicer** [comment]
Thank you @brockfanning for your help. My YAML files appears identical. I found it's choking on the "bar" character in the yaml file at this entry:

               no results message: |

When I remove the bar, it's fine and will move to the next line. My dev environment is php 7.4 using MAMP. While my production is php 8 on windows. Could the version difference be the problem?

**Comment by brockfanning** [comment]
@LanceSpicer That could certainly be it. I have not tried PHP 8 yet. I'm just curious how you're getting the vendor files to production - are you running "composer install" on production, or are you running it on dev and then copying everything over?

**Comment by LanceSpicer** [comment]
At first, I copied everything over because I wasn't sure if I needed to run it again. Once I got the error above, I then installed composer and ran "composer install". Which is the recommended method?

I will install php 7.4 on production and see if that changes anything.

**Comment by brockfanning** [comment]
My impression is that if you're copying the vendor folder from one server to another, you'll need both servers to have the same version of PHP.

**Comment by LanceSpicer** [comment]
Ok, I found php 7.4 (7.4.15) for windows to install on production. My dev env is 7.4.2 MAMP. Should Windows vs. MAMP matter? Or should I "composer install" on production?

**Comment by brockfanning** [comment]
Hi @LanceSpicer I can't help much more beyond my last comment, as I am not much of a sys admin.

**Comment by LanceSpicer** [comment]
@brockfanning, installing the exact same version of both php and MySql fixed it!. I'm running now. Thanks again for your help.
